export type FinalErrorCode =
  | "APP_BOOT_FAILURE"
  | "ROUTE_FAILURE"
  | "API_FAILURE"
  | "AUTH_FAILURE"
  | "PROJECTION_FAILURE"
  | "REPLAY_FAILURE"
  | "REALTIME_FAILURE"
  | "INTEGRATION_FAILURE";
