apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kustomization.yaml

images:
  - name: kiri-device-service
    newName: kiri-device-service
    newTag: production
