import {
  registerState,
} from "../registry/stateRegistry";

const states = [
  {
    id:
      "property.draft",
    domain:
      "properties",
    name:
      "draft",
    label:
      "Draft",
    description:
      "Property definition is being prepared.",
    terminal:
      false,
    initial:
      true,
    enabled:
      true,
  },
  {
    id:
      "property.active",
    domain:
      "properties",
    name:
      "active",
    label:
      "Active",
    description:
      "Property is operationally active.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },
  {
    id:
      "property.suspended",
    domain:
      "properties",
    name:
      "suspended",
    label:
      "Suspended",
    description:
      "Property is temporarily suspended.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },

  {
    id:
      "lease.pending",
    domain:
      "leases",
    name:
      "pending",
    label:
      "Pending",
    description:
      "Lease has not yet entered active state.",
    terminal:
      false,
    initial:
      true,
    enabled:
      true,
  },
  {
    id:
      "lease.active",
    domain:
      "leases",
    name:
      "active",
    label:
      "Active",
    description:
      "Lease is active.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },
  {
    id:
      "lease.suspended",
    domain:
      "leases",
    name:
      "suspended",
    label:
      "Suspended",
    description:
      "Lease is temporarily suspended.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },
  {
    id:
      "lease.terminated",
    domain:
      "leases",
    name:
      "terminated",
    label:
      "Terminated",
    description:
      "Lease has terminated.",
    terminal:
      true,
    initial:
      false,
    enabled:
      true,
  },

  {
    id:
      "payment.pending",
    domain:
      "payments",
    name:
      "pending",
    label:
      "Pending",
    description:
      "Payment is pending confirmation.",
    terminal:
      false,
    initial:
      true,
    enabled:
      true,
  },
  {
    id:
      "payment.completed",
    domain:
      "payments",
    name:
      "completed",
    label:
      "Completed",
    description:
      "Payment is completed.",
    terminal:
      true,
    initial:
      false,
    enabled:
      true,
  },
  {
    id:
      "payment.failed",
    domain:
      "payments",
    name:
      "failed",
    label:
      "Failed",
    description:
      "Payment failed.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },

  {
    id:
      "device.registered",
    domain:
      "devices",
    name:
      "registered",
    label:
      "Registered",
    description:
      "Device is registered.",
    terminal:
      false,
    initial:
      true,
    enabled:
      true,
  },
  {
    id:
      "device.online",
    domain:
      "devices",
    name:
      "online",
    label:
      "Online",
    description:
      "Device is operationally online.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },
  {
    id:
      "device.offline",
    domain:
      "devices",
    name:
      "offline",
    label:
      "Offline",
    description:
      "Device is not currently online.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },
  {
    id:
      "device.quarantined",
    domain:
      "devices",
    name:
      "quarantined",
    label:
      "Quarantined",
    description:
      "Device is isolated by security policy.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },

  {
    id:
      "lock.secured",
    domain:
      "locks",
    name:
      "secured",
    label:
      "Secured",
    description:
      "Lock is secured.",
    terminal:
      false,
    initial:
      true,
    enabled:
      true,
  },
  {
    id:
      "lock.released",
    domain:
      "locks",
    name:
      "released",
    label:
      "Released",
    description:
      "Lock is released.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },
  {
    id:
      "lock.frozen",
    domain:
      "locks",
    name:
      "frozen",
    label:
      "Frozen",
    description:
      "Lock operations are frozen.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },

  {
    id:
      "security.clear",
    domain:
      "security",
    name:
      "clear",
    label:
      "Clear",
    description:
      "Security controls are clear.",
    terminal:
      false,
    initial:
      true,
    enabled:
      true,
  },
  {
    id:
      "security.frozen",
    domain:
      "security",
    name:
      "frozen",
    label:
      "Frozen",
    description:
      "Security controls are frozen.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },
  {
    id:
      "security.recovering",
    domain:
      "security",
    name:
      "recovering",
    label:
      "Recovering",
    description:
      "Security recovery is in progress.",
    terminal:
      false,
    initial:
      false,
    enabled:
      true,
  },

  {
    id:
      "dashboard.ready",
    domain:
      "dashboard",
    name:
      "ready",
    label:
      "Ready",
    description:
      "Dashboard operational view is ready.",
    terminal:
      false,
    initial:
      true,
    enabled:
      true,
  },
];

export function registerCanonicalStates(): void {
  for (
    const state of
      states
  ) {
    registerState(
      state,
    );
  }
}
