apiVersion: v1
kind: Secret
metadata:
  name: kiri-device-service-secrets
  namespace: kirilock
type: Opaque
stringData:
  DEVICE_SERVICE_ID: "REPLACE_ME"
  DEVICE_DB_DSN: "REPLACE_ME"
  DEVICE_MESSAGE_CLIENT_ID: "REPLACE_ME"
