import type { OperatorNavigationItem } from "./navigationItem";

export const OPERATOR_NAVIGATION_CATALOG: OperatorNavigationItem[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    capability: "dashboard.read",
    requiresAuthentication: true,
    privileged: false,
    dangerous: false,
    active: true,
  },
  {
    key: "properties",
    label: "Properties",
    path: "/properties",
    capability: "properties.read",
    requiresAuthentication: true,
    privileged: false,
    dangerous: false,
    active: true,
  },
  {
    key: "leases",
    label: "Leases",
    path: "/leases",
    capability: "leases.read",
    requiresAuthentication: true,
    privileged: false,
    dangerous: false,
    active: true,
  },
  {
    key: "payments",
    label: "Payments",
    path: "/payments",
    capability: "payments.read",
    requiresAuthentication: true,
    privileged: false,
    dangerous: false,
    active: true,
  },
  {
    key: "devices",
    label: "Devices",
    path: "/devices",
    capability: "devices.read",
    requiresAuthentication: true,
    privileged: false,
    dangerous: false,
    active: true,
  },
  {
    key: "locks",
    label: "Locks",
    path: "/locks",
    capability: "locks.read",
    requiresAuthentication: true,
    privileged: false,
    dangerous: false,
    active: true,
  },
  {
    key: "security",
    label: "Security",
    path: "/security",
    capability: "security.read",
    requiresAuthentication: true,
    privileged: true,
    dangerous: false,
    active: true,
  },
  {
    key: "rbac",
    label: "Access Control",
    path: "/rbac",
    capability: "security.admin",
    requiresAuthentication: true,
    privileged: true,
    dangerous: true,
    active: true,
  },
];
