export const CANONICAL_CAPABILITIES = [
  "dashboard.read",
  "properties.read",
  "properties.write",
  "leases.read",
  "leases.write",
  "payments.read",
  "payments.write",
  "devices.read",
  "devices.write",
  "devices.command",
  "locks.read",
  "locks.write",
  "locks.command",
  "security.read",
  "security.audit.read",
  "security.control",
  "operator.control",
  "operator.global.control",
  "runtime.read",
  "runtime.control",
  "recovery.execute",
] as const;
