import type { RBACCapability } from "./capabilityDefinition";

export const RBAC_CAPABILITY_CATALOG: RBACCapability[] = [
  {
    key: "dashboard.read",
    domain: "dashboard",
    level: "read",
    scope: "global",
    dangerous: false,
    mutating: false,
    description: "View dashboard operations.",
    active: true,
  },
  {
    key: "properties.read",
    domain: "properties",
    level: "read",
    scope: "tenant",
    dangerous: false,
    mutating: false,
    description: "View properties.",
    active: true,
  },
  {
    key: "properties.write",
    domain: "properties",
    level: "write",
    scope: "tenant",
    dangerous: false,
    mutating: true,
    description: "Modify property data.",
    active: true,
  },
  {
    key: "leases.read",
    domain: "leases",
    level: "read",
    scope: "tenant",
    dangerous: false,
    mutating: false,
    description: "View leases.",
    active: true,
  },
  {
    key: "leases.write",
    domain: "leases",
    level: "write",
    scope: "tenant",
    dangerous: false,
    mutating: true,
    description: "Modify lease state.",
    active: true,
  },
  {
    key: "payments.read",
    domain: "payments",
    level: "read",
    scope: "tenant",
    dangerous: false,
    mutating: false,
    description: "View payments.",
    active: true,
  },
  {
    key: "payments.write",
    domain: "payments",
    level: "write",
    scope: "tenant",
    dangerous: false,
    mutating: true,
    description: "Perform payment workflow operations.",
    active: true,
  },
  {
    key: "devices.read",
    domain: "devices",
    level: "read",
    scope: "tenant",
    dangerous: false,
    mutating: false,
    description: "View devices.",
    active: true,
  },
  {
    key: "devices.command",
    domain: "devices",
    level: "command",
    scope: "resource",
    dangerous: true,
    mutating: true,
    description: "Issue device commands.",
    active: true,
  },
  {
    key: "locks.read",
    domain: "locks",
    level: "read",
    scope: "tenant",
    dangerous: false,
    mutating: false,
    description: "View lock state.",
    active: true,
  },
  {
    key: "locks.command",
    domain: "locks",
    level: "command",
    scope: "resource",
    dangerous: true,
    mutating: true,
    description: "Issue lock commands.",
    active: true,
  },
  {
    key: "security.read",
    domain: "security",
    level: "read",
    scope: "organization",
    dangerous: false,
    mutating: false,
    description: "View security state.",
    active: true,
  },
  {
    key: "security.review",
    domain: "security",
    level: "review",
    scope: "organization",
    dangerous: false,
    mutating: false,
    description: "Review security activity.",
    active: true,
  },
  {
    key: "security.admin",
    domain: "security",
    level: "admin",
    scope: "organization",
    dangerous: true,
    mutating: true,
    description: "Perform privileged security administration.",
    active: true,
  },
  {
    key: "session.manage",
    domain: "security",
    level: "admin",
    scope: "organization",
    dangerous: true,
    mutating: true,
    description: "Manage operator sessions.",
    active: true,
  },
];
