import type { RoleDefinition } from "./roleDefinition";

export const DEFAULT_RBAC_ROLES: RoleDefinition[] = [
  {
    key: "viewer",
    name: "Viewer",
    description: "Read-only operator visibility.",
    priority: 10,
    active: true,
    capabilities: [
      "dashboard.read",
      "properties.read",
      "leases.read",
      "payments.read",
      "devices.read",
      "locks.read",
      "security.read",
    ],
  },
  {
    key: "operator",
    name: "Operator",
    description: "Operational workflows without administration.",
    priority: 20,
    active: true,
    capabilities: [
      "dashboard.read",
      "properties.read",
      "leases.read",
      "leases.write",
      "payments.read",
      "payments.write",
      "devices.read",
      "devices.command",
      "locks.read",
      "locks.command",
      "security.read",
    ],
  },
  {
    key: "manager",
    name: "Manager",
    description: "Operational management capabilities.",
    priority: 30,
    active: true,
    capabilities: [
      "dashboard.read",
      "properties.read",
      "properties.write",
      "leases.read",
      "leases.write",
      "payments.read",
      "payments.write",
      "devices.read",
      "devices.command",
      "locks.read",
      "locks.command",
      "security.read",
      "security.review",
    ],
  },
  {
    key: "administrator",
    name: "Administrator",
    description: "Broad platform administration.",
    priority: 40,
    active: true,
    capabilities: [
      "dashboard.read",
      "properties.read",
      "properties.write",
      "leases.read",
      "leases.write",
      "payments.read",
      "payments.write",
      "devices.read",
      "devices.command",
      "locks.read",
      "locks.command",
      "security.read",
      "security.review",
      "security.admin",
      "session.manage",
    ],
  },
  {
    key: "security-admin",
    name: "Security Administrator",
    description: "Security review and privileged security controls.",
    priority: 50,
    active: true,
    capabilities: [
      "dashboard.read",
      "security.read",
      "security.review",
      "security.admin",
      "session.manage",
    ],
  },
];
