import type { RoleDefinition } from "./roleDefinition";

// Frontend roles now match authoritative backend roles from backend/security-service/internal/security/role.go
// Backend roles: tenant, landlord, service, device, operator, security_admin, super_admin
export const DEFAULT_RBAC_ROLES: RoleDefinition[] = [
  {
    key: "tenant",
    name: "Tenant",
    description: "Tenant with access to their unit and lock.",
    priority: 10,
    active: true,
    capabilities: [
      "dashboard.read",
      "leases.read",
      "locks.read",
      "locks.command",
      "security.read",
    ],
  },
  {
    key: "landlord",
    name: "Landlord",
    description: "Landlord managing properties, units, and tenants.",
    priority: 20,
    active: true,
    capabilities: [
      "dashboard.read",
      "properties.read",
      "properties.write",
      "leases.read",
      "leases.write",
      "payments.read",
      "payments.write",
      "devices.read",
      "locks.read",
      "locks.command",
      "security.read",
    ],
  },
  {
    key: "operator",
    name: "Operator",
    description: "Operational workflows without administration.",
    priority: 30,
    active: true,
    capabilities: [
      "dashboard.read",
      "properties.read",
      "leases.read",
      "leases.write",
      "payments.read",
      "payments.write",
      "devices.read",
      "devices.command",
      "locks.read",
      "locks.command",
      "security.read",
    ],
  },
  {
    key: "security_admin",
    name: "Security Administrator",
    description: "Security review and privileged security controls.",
    priority: 40,
    active: true,
    capabilities: [
      "dashboard.read",
      "security.read",
      "security.write",
      "security.review",
      "security.admin",
      "session.manage",
      "audit.read",
    ],
  },
  {
    key: "super_admin",
    name: "Super Administrator",
    description: "Full platform administration including landlord verification.",
    priority: 50,
    active: true,
    capabilities: [
      "dashboard.read",
      "properties.read",
      "properties.write",
      "leases.read",
      "leases.write",
      "payments.read",
      "payments.write",
      "devices.read",
      "devices.command",
      "locks.read",
      "locks.command",
      "security.read",
      "security.write",
      "security.review",
      "security.admin",
      "session.manage",
      "audit.read",
      "landlord.verify",
    ],
  },
];
