import type { OperatorActionDefinition } from "./actionDefinition";

export const OPERATOR_ACTION_CATALOG: OperatorActionDefinition[] = [
  {
    key: "property.create",
    label: "Create property",
    capability: "properties.write",
    domain: "properties",
    mutating: true,
    dangerous: false,
    privileged: false,
    active: true,
  },
  {
    key: "property.edit",
    label: "Edit property",
    capability: "properties.write",
    domain: "properties",
    mutating: true,
    dangerous: false,
    privileged: false,
    active: true,
  },
  {
    key: "lease.edit",
    label: "Edit lease",
    capability: "leases.write",
    domain: "leases",
    mutating: true,
    dangerous: false,
    privileged: false,
    active: true,
  },
  {
    key: "payment.operate",
    label: "Operate payment",
    capability: "payments.write",
    domain: "payments",
    mutating: true,
    dangerous: false,
    privileged: false,
    active: true,
  },
  {
    key: "device.command",
    label: "Command device",
    capability: "devices.command",
    domain: "devices",
    mutating: true,
    dangerous: true,
    privileged: true,
    active: true,
  },
  {
    key: "lock.command",
    label: "Command lock",
    capability: "locks.command",
    domain: "locks",
    mutating: true,
    dangerous: true,
    privileged: true,
    active: true,
  },
  {
    key: "security.review",
    label: "Review security",
    capability: "security.review",
    domain: "security",
    mutating: false,
    dangerous: false,
    privileged: true,
    active: true,
  },
  {
    key: "security.admin",
    label: "Administer security",
    capability: "security.admin",
    domain: "security",
    mutating: true,
    dangerous: true,
    privileged: true,
    active: true,
  },
  {
    key: "session.manage",
    label: "Manage sessions",
    capability: "session.manage",
    domain: "security",
    mutating: true,
    dangerous: true,
    privileged: true,
    active: true,
  },
];
