import type { ActiveRouteDefinition } from "./activeRouteDefinition";

export const activeRoutes: ActiveRouteDefinition[] = [
  {
    id: "dashboard",
    route: "/",
    domain: "dashboard",
    pageId: "dashboard.overview",
    enabled: true,
  },
  {
    id: "properties",
    route: "/properties",
    domain: "properties",
    pageId: "properties.list",
    enabled: true,
  },
  {
    id: "leases",
    route: "/leases",
    domain: "leases",
    pageId: "leases.list",
    enabled: true,
  },
  {
    id: "payments",
    route: "/payments",
    domain: "payments",
    pageId: "payments.list",
    enabled: true,
  },
  {
    id: "devices",
    route: "/devices",
    domain: "devices",
    pageId: "devices.workspace",
    enabled: true,
  },
  {
    id: "locks",
    route: "/locks",
    domain: "locks",
    pageId: "locks.workspace",
    enabled: true,
  },
  {
    id: "security",
    route: "/security",
    domain: "security",
    pageId: "security.workspace",
    enabled: true,
  },
  {
    id: "security-audit",
    route: "/security/audit",
    domain: "security",
    pageId: "security.audit",
    enabled: true,
  },
  {
    id: "security-control",
    route: "/security/control",
    domain: "security",
    pageId: "security.control",
    enabled: true,
  },
  {
    id: "rbac",
    route: "/rbac",
    domain: "security",
    pageId: "security.rbac",
    enabled: true,
  },
  {
    id: "operator-control",
    route: "/operator-control",
    domain: "dashboard",
    pageId: "operator.control",
    enabled: true,
  },
  {
    id: "operator-global",
    route: "/operator-control/global",
    domain: "dashboard",
    pageId: "operator.global-control",
    enabled: true,
  },
  {
    id: "health",
    route: "/health",
    domain: "dashboard",
    pageId: "frontend.health",
    enabled: true,
  },
  {
    id: "integrity",
    route: "/integrity",
    domain: "dashboard",
    pageId: "frontend.integrity",
    enabled: true,
  },
  {
    id: "runtime",
    route: "/runtime",
    domain: "dashboard",
    pageId: "frontend.runtime",
    enabled: true,
  },
];
