import {
  registerApiOperation,
} from "../registry/operationRegistry";

const operations = [
  {
    key: "dashboard.list",
    domain: "dashboard",
    operation: "list" as const,
    path: "/api/v1/dashboard/overview",
    method: "GET" as const,
    authenticated: true,
    capability: "dashboard.read",
  },
  {
    key: "properties.list",
    domain: "properties",
    operation: "list" as const,
    path: "/api/v1/properties",
    method: "GET" as const,
    authenticated: true,
    capability: "properties.read",
  },
  {
    key: "properties.get",
    domain: "properties",
    operation: "get" as const,
    path: "/api/v1/properties/:id",
    method: "GET" as const,
    authenticated: true,
    capability: "properties.read",
  },
  {
    key: "leases.list",
    domain: "leases",
    operation: "list" as const,
    path: "/api/v1/leases",
    method: "GET" as const,
    authenticated: true,
    capability: "leases.read",
  },
  {
    key: "leases.get",
    domain: "leases",
    operation: "get" as const,
    path: "/api/v1/leases/:id",
    method: "GET" as const,
    authenticated: true,
    capability: "leases.read",
  },
  {
    key: "payments.list",
    domain: "payments",
    operation: "list" as const,
    path: "/api/v1/payments",
    method: "GET" as const,
    authenticated: true,
    capability: "payments.read",
  },
  {
    key: "payments.get",
    domain: "payments",
    operation: "get" as const,
    path: "/api/v1/payments/:id",
    method: "GET" as const,
    authenticated: true,
    capability: "payments.read",
  },
  {
    key: "devices.get",
    domain: "devices",
    operation: "get" as const,
    path: "/api/v1/devices/:id",
    method: "GET" as const,
    authenticated: true,
    capability: "devices.read",
  },
  {
    key: "devices.command",
    domain: "devices",
    operation: "command" as const,
    path: "/api/v1/command",
    method: "POST" as const,
    authenticated: true,
    capability: "devices.command",
  },
  {
    key: "devices.status",
    domain: "devices",
    operation: "status" as const,
    path: "/api/v1/status",
    method: "GET" as const,
    authenticated: true,
    capability: "devices.read",
  },
  {
    key: "locks.get",
    domain: "locks",
    operation: "get" as const,
    path: "/api/v1/locks/:id",
    method: "GET" as const,
    authenticated: true,
    capability: "locks.read",
  },
  {
    key: "locks.command",
    domain: "locks",
    operation: "command" as const,
    path: "/api/v1/locks/:id/command",
    method: "POST" as const,
    authenticated: true,
    capability: "locks.command",
  },
  {
    key: "security.list",
    domain: "security",
    operation: "list" as const,
    path: "/api/v1/security/events",
    method: "GET" as const,
    authenticated: true,
    capability: "security.read",
  },
];

export function registerCanonicalApiOperations(): void {
  for (const operation of operations) {
    registerApiOperation(operation);
  }
}
