apiVersion: v1
kind: Service
metadata:
  name: kiri-device-service
  namespace: kirilock
  labels:
    app.kubernetes.io/name: kiri-device-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kiri-device-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
