apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kiri-device-service
  namespace: kirilock
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kiri-device-service
