apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kirilock

resources:
  - namespace.yaml
  - device-service-serviceaccount.yaml
  - device-service-configmap.yaml
  - device-service-deployment.yaml
  - device-service-service.yaml
  - device-service-pdb.yaml
  - device-service-hpa.yaml
  - device-service-networkpolicy.yaml
