import {
  registerDomainPage,
} from "./domainPageRegistry";

const pages = [
  {
    domain:
      "dashboard",
    title:
      "Operations Dashboard",
    route:
      "/",
    readCapability:
      "dashboard.read",
    operational:
      true,
  },
  {
    domain:
      "properties",
    title:
      "Properties",
    route:
      "/properties",
    readCapability:
      "properties.read",
    writeCapability:
      "properties.write",
    operational:
      true,
  },
  {
    domain:
      "leases",
    title:
      "Leases",
    route:
      "/leases",
    readCapability:
      "leases.read",
    writeCapability:
      "leases.write",
    operational:
      true,
  },
  {
    domain:
      "payments",
    title:
      "Payments",
    route:
      "/payments",
    readCapability:
      "payments.read",
    writeCapability:
      "payments.write",
    operational:
      true,
  },
  {
    domain:
      "devices",
    title:
      "Devices",
    route:
      "/devices",
    readCapability:
      "devices.read",
    writeCapability:
      "devices.write",
    commandCapability:
      "devices.command",
    operational:
      true,
  },
  {
    domain:
      "locks",
    title:
      "Locks",
    route:
      "/locks",
    readCapability:
      "locks.read",
    writeCapability:
      "locks.write",
    commandCapability:
      "locks.command",
    operational:
      true,
  },
  {
    domain:
      "security",
    title:
      "Security",
    route:
      "/security",
    readCapability:
      "security.read",
    writeCapability:
      "security.control",
    commandCapability:
      "recovery.execute",
    operational:
      true,
  },
] as const;

export function registerCanonicalDomainPages(): void {
  for (const page of pages) {
    registerDomainPage(
      page,
    );
  }
}
